### ISSUE TITLE
Avantes get_version_info( ) error

### ISSUE THREAD

**Issue by guilhermebene** [MSLNZ/msl-equipment#4]
I found the following error when using the function `get_version_info()` from Avantes with Python 3.8.5 on Spyder:
```
Traceback (most recent call last):

  File "C:\spas\Programs\Python\test_ava.py", line 17, in <module>
    print(ava.get_version_info())

  File "C:\Users\user1\Anaconda3\envs\env2\lib\site-packages\msl\equipment\resources\avantes\avaspec.py", line 631, in get_version_info
    self.sdk.AVS_GetVersionInfo(self._handle, fpga, fm, dll)

ArgumentError: argument 2: <class 'TypeError'>: wrong type
```

I'm using the following code to test this error:
```
from msl.equipment import EquipmentRecord, ConnectionRecord, Backend
from msl.equipment.resources.avantes import MeasureCallback
from msl.equipment.resources.avantes.avaspec import SmoothingType, TriggerType, DarkCorrectionType, ControlSettingsType

record = EquipmentRecord(
        manufacturer='Avantes',
        model='AvaSpec-UCLS2048BCL-EVO-RS',  # update for your device
        serial='2011126U1',  # update for your device
        connection=ConnectionRecord(
            # only specify the SDK filename and add the root directory to sys.path (see above)
            address='SDK::./lib/avaspec3/avaspecx64.dll',
            backend=Backend.MSL,
        )
    )

ava = record.connect()
print(ava.get_version_info())
ava.disconnect()
```

**Comment by jborbely** [comment]
Thanks for raising this issue. I have just pushed a fix for it.

You can install the version with the fix by running:

``pip install -U https://github.com/MSLNZ/msl-equipment/archive/master.zip``

I have also brought up some of the lower-lying Avantes classes. So, one can now use the following

```python
from msl.equipment.resources.avantes import MeasureCallback, SmoothingType, ...
```

instead of 
```python
from msl.equipment.resources.avantes import MeasureCallback
from msl.equipment.resources.avantes.avaspec import SmoothingType, ...
```

or once you have an instance of the ``Avantes`` class you can access the constants, enums, and structs of the SDK
```python
ava = record.connect()
print(ava.WM_MEAS_READY)
print(ava.InterfaceType.USBMINI)
print(ava.SmoothingType())
print('version: {}'.format(ava.get_version_info()))
```

Please let me know if this fix has resolved the issue that you found.

**Comment by guilhermebene** [comment]
Thank you for the fix! Everything is working now.
