### ISSUE TITLE
Sever32 error

### ISSUE THREAD

**Issue by guilhermebene** [MSLNZ/msl-equipment#6]
I have been using `msl-equipment`for a few months, especially the Avantes subpackage. I recently had to reinstall my working environment and I decided to use a Miniconda virtual environment. 
I am installing msl-equipment with `pip` directly from github using the following command:
```
pip install msl-equipment@git+https://github.com/MSLNZ/msl-equipment.git
```

When I try to import a few modules using `from msl.equipment import EquipmentRecord, ConnectionRecord, Backend`, I get the following error:

```
from msl.equipment import EquipmentRecord, ConnectionRecord, Backend
Traceback (most recent call last):

  File "<ipython-input-3-08110628f66d>", line 1, in <module>
    from msl.equipment import EquipmentRecord, ConnectionRecord, Backend

  File "C:\Users\<user>\Miniconda3\envs\spas\lib\site-packages\msl\equipment\__init__.py", line 8, in <module>
    from msl.equipment.record_types import (

  File "C:\Users\<user>\Miniconda3\envs\spas\lib\site-packages\msl\equipment\record_types.py", line 30, in <module>
    from .factory import (

  File "C:\Users\<user>\Miniconda3\envs\spas\lib\site-packages\msl\equipment\factory.py", line 11, in <module>
    from .resources import find_resource_class

  File "C:\Users\<user>\Miniconda3\envs\spas\lib\site-packages\msl\equipment\resources\__init__.py", line 83, in <module>
    importlib.import_module(root_pkg + '.' + filename[:-3])

  File "C:\Users\<user>\Miniconda3\envs\spas\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "C:\Users\<user>\Miniconda3\envs\spas\lib\site-packages\msl\equipment\resources\dataray\datarayocx_32.py", line 75, in <module>
    if Server32.is_interpreter():

AttributeError: type object 'Server32' has no attribute 'is_interpreter'
```

**Comment by jborbely** [comment]
To fix this error run the following in your virtual environment
```console
pip install -U msl-loadlib
```

There were a few days around May 12th when I was adding a feature to msl-loadlib (a dependency of msl-equipment) and I included this feature in msl-equipment before a new release of msl-loadlib was published. You might have just been _unlucky_ and ran that pip command sometime during this transition period. Installing msl-equipment in a new environment that is created now would install the appropriate dependencies.

**Comment by guilhermebene** [comment]
Thank you, I created a new environment and it all seems to work now.

**Comment by jborbely** [comment]
Great, thanks for letting me know.
